My_Portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('my_blog/', include('my_blog.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_blog/urls.py
from django.urls import path
from . import views

app_name='content'
urlpatterns = [
    path('',views.hello,name='hello'),
    path('<int:blog_id>/',views.details,name='details'),


]

my_blog/models.py
from django.db import models

class blog(models.Model):
    Title=models.CharField(max_length=200)
    description=models.CharField(max_length=250)
    Date=models.DateField()

    def __str__(self):
        return self.Title
    

portfolio/models.py
from django.db import models

class Project(models.Model):
    Title=models.CharField(max_length=200)
    description=models.CharField(max_length=900)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)

my_blog/views.py
from django.shortcuts import render,get_object_or_404

from .models import blog

def hello(request):
    blogs=blog.objects.order_by('-Date') [:5]
    return render(request,"my_blog/blog.html",{"blogs":blogs})
def details(request,blog_id):
    blogs=get_object_or_404(blog,pk=blog_id)
    return render(request,"my_blog/details.html",{'blogs':blogs})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    Projects= Project.objects.all()
    return render(request,"portfolio/home.html",{"Projects":Projects})

my_blog/templates/my_blog/blog.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <h1>I am good</h1>
    <h2>I have written {{blogs.count}}  blog{{blogs.count|pluralize}} </h2>
    {% for content in blogs %}
    <a href="{% url 'content:details' content.id %}"><h1>{{content.Title}}</h1></a>
    <P>{{content.description|striptags|truncatechars:120}}</P>
    <h2>{{content.Date|date:'M d Y'|title}}</h2>
    {% endfor %}
{% endblock %}    

my_blog/templates/my_blog/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ blogs.Title }}</h1>
    <h2>{{ blogs.description|safe }}</h2>
    <h1>{{blogs.Date|date:'F jS Y'}}</h1>
  
</body>
</html>

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
  <style>
    img {
      height: 300px;
      width: 300px;
    }

    a {
      text-decoration: none;
    }

    body {
      background-color: beige;
    }

    nav ul {
      display: flex;
      padding: 7px 16px;
      list-style: none;
      justify-content: end;
    }
    .item{
      padding: 0px 14px;
    font-size: 1.2rem;
    font-family: fangsong;
    
    }
    .kem{
      display: flex;
      justify-content: center;
     
    }
    #navbar{
      background-color: black;
      opacity: 0.8;
    }
    #text{
      display: flex;
      flex-direction: row;
      border: 3px solid black;
    }

   
  </style>

</head>

<body>

  <nav id="navbar">

    <ul>
      <li class="item"><a href="{% static 'portfolio/resume.pdf' %}">resume</a></li>
      <li class="item"><a href="{% url 'content:hello' %}">Blog</a></li>
      <li class="item"><a href="https://www.facebook.com/campaign/landing.php?campaign_id=14884913640&extra_1=s%7Cc%7C550525804791%7Cb%7Cfacebook%20%27%7C&placement=&creative=550525804791&keyword=facebook%20%27&partner_id=googlesem&extra_2=campaignid%3D14884913640%26adgroupid%3D128696220912%26matchtype%3Db%26network%3Dg%26source%3Dnotmobile%26search_or_content%3Ds%26device%3Dc%26devicemodel%3D%26adposition%3D%26target%3D%26targetid%3Dkwd-327195741349%26loc_physical_ms%3D9040245%26loc_interest_ms%3D%26feeditemid%3D%26param1%3D%26param2%3D&gclid=CjwKCAiAu5agBhBzEiwAdiR5tNtVrvARpuhWXAIxCgVlfyRJJROuhLjCOByxqOi4wXkdjTECH6IdDxoCPDAQAvD_BwE">Facebook</a></li>
      <li class="item"><a href="https://twitter.com/35_shahu?t=TzTHbPSuf8SqZ82d_3x8Cg&s=08">Twitter</a></li>
    </ul>
  </nav>
  {%block content%}{%endblock%}





</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
{% load static %}
<h1><b class="kem">Welcome to my portfolio</b></h1>

<div id="text" class="text12">
    {% for x in Projects %}

    <h1>{{ x.Title }}</h1><br>
    
    <img src=" {{ x.image.url }}" width="60px" height="60px"></Br>
    <h3> {{ x.description }}</h3><br>
    {% if x.url %}
    <a href=" {{x.url}}">Click Here</a>
    {% endif %}
{% endfor %}
</div>

{% endblock %}